groupal/apps/web/urls.py
from django.conf.urls import patterns, url
from views import Login, Logout, Index, Register, Groups, Group, GroupCreate, GroupUpdate, GroupDelete

urlpatterns = patterns(
	'', 
	url(r'^$', Index.as_view(), name='index'),
	url(r'^login/$', Login.as_view(), name='login'),
	url(r'^logout/$', Logout.as_view(), name='logout'),
	url(r'^register/$', Register.as_view(), name='register'),
	url(r'^groups/$', Groups.as_view(), name='groups'),
    url(r'^group/add/$', GroupCreate.as_view(), name='group_create'),
    url(r'^group/(?P<pk>\d+)/$', GroupUpdate.as_view(), name='group_update'),
    url(r'^group/(?P<pk>\d+)/delete/$', GroupDelete.as_view(), name='group_delete'),
)

groupal/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns(
    '',
    url(r'', include('groupal.apps.web.urls', namespace="web")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('groupal.apps.api.urls', namespace='api')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupal/apps/web/templates/web/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Groupal{% endblock %}</title>
    <link href="{% static "web/styles/style.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "jquery-ui/themes/smoothness/jquery-ui.css" %}" rel="stylesheet" media="screen">

    {% bootstrap_css %}

    <script type="text/javascript" src='{% static 'jquery/dist/jquery.js' %}'></script>
    <script type="text/javascript" src='{% static 'jquery-ui/jquery-ui.js' %}'></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".datepicker").datepicker({
                dateFormat:'yy-mm-dd'
            });

        });
    </script>
</head>

<body>
    <div id="menu">
        {% block menu %}
        <ul>
            <li><a href="{% url 'web:index' %}">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'web:groups' %}">Groups</a></li>
                <li><a href="{% url 'web:logout' %}">Logout {{ user.username }}</a></li>
            {% endif %}
        </ul>
        {% endblock %}
    </div>

    <div id="content" class="container">
    {% block content %}{% endblock %}
    </div>
</body>
</html>

groupal/apps/web/templates/web/group.html
<form action="/web/group/" method="post">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <input type="submit" value="Save" />
</form>

groupal/apps/web/templates/web/group_create.html
{% extends "web/base.html" %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <input type="submit" value="Save" />
</form>
{% endblock %}

groupal/apps/web/templates/web/group_delete.html
{% extends "web/base.html" %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.title }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

groupal/apps/web/templates/web/group_list.html
{% extends "web/base.html" %}

{% block content %}

    <a href="{% url 'web:group_create' %}">ADD GROUP</a>

    {% for item in items %}
        <div>
        {{ item.title }}
        {% if item.thumbnail %} <p><img border="0" alt="Thumbnail" src="{{ item.thumbnail.url }}" /></p> {% endif %}
        <a href="{% url 'web:group_delete' item.pk %} ">Delete</a>
        </div>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

{% endblock %}

groupal/apps/web/templates/web/group_update.html
{% extends "web/base.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <input type="submit" value="Save" />
</form>
{% endblock %}

groupal/apps/web/templates/web/index.html
{% extends "web/base.html" %}

{% block content %}

    <div>
        <a href="{% url 'web:login' %}">Login</a>
        <a href="{% url 'web:register' %}">Register</a>
    </div>

    Groupal is a simple contact groups management system. Users can register and create their profile and groups or request permission
    to join groups. Group administrators have permission to manage their groups by accepting join requests assigining moderators.

    There is an android application "Groupal" which users can download and log-in to. Once a user logs-in to tha android application
    it'll download all groups that the user is part of. Then users can contact the friends through the app either by calling or sending messages

{% endblock %}

groupal/apps/web/templates/web/login.html
{% extends "web/base.html" %}

{% block content %}

<table>
<tr><td>Username: </td><td><input type="text" id="username" name="Username" /></td></tr>
<tr><td>Password: </td><td><input type="password" id="password" name="password" /></td></tr>
</table>

{% endblock %}

groupal/apps/web/templates/web/register.html
{% extends "web/base.html" %}
{% load bootstrap3 %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal'%}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Save
        </button>
    {% endbuttons %}
</form>
{% endblock %}